#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawJoint,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftBelt,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           rightBelt,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define true 1
#define false 0

/*
  Project Title: VEX Clawbot
  Team Members: Matthew Finerty
  Date: April 24th, 2017
  Section: Robotics


  Task Description: Create a robot that is able to to pick up and place cones


  Pseudocode:
  While true
  	a bunch of if statements and stuff here
  end

  Controls:
  * Left Joystick Y - Move forward/backwards
  * Left Joystick X - Turn left/right
  * Right Joystick Y - Raise/lower claw joint
  * Right Joystick X - None

  * Button 8D (A) - Open/close claw
  * Button 6D (RT) - Move conveyor belt forwards
  * Button 5D (LT) - Move conveyor belt backwards


*/

/*
	Functions:
	-Move forwards/backwards
	-Turn left/right
	-Stop motors when joystick is inactive
*/
task LeftJoystick()
{
	while (true)
	{
		// Move forward/backwards
		if (vexRT(Ch3) > 0 || vexRT(Ch3) < 0)
		{
			startMotor(leftMotor, vexRT(Ch3));
			startMotor(rightMotor, vexRT(Ch3));
		}

		// Turn right
		if (vexRT(Ch4) > 0)
		{
			startMotor(leftMotor, vexRT(Ch4));
			startMotor(rightMotor, vexRT(Ch4)*-1);
		}

		// Turn left
		if (vexRT(Ch4) < 0)
		{
			startMotor(leftMotor, vexRT(Ch4));
			startMotor(rightMotor, vexRT(Ch4)*-1);
		}

		// Stop when joystick is not active
		if (vexRT(Ch3) == 0 && vexRT(Ch4) == 0)
		{
			stopMotor(leftMotor);
			stopMotor(rightMotor);
		}
	}
}

/*
	Functions:
	-Lower/raise claw joint
*/
task RightJoystick()
{
	while (true)
	{
		// Lower/raise claw joint
		if (vexRT(Ch1) < 0 || vexRT(Ch1) > 0)
		{
			startMotor(clawJoint, vexRT(Ch1));
		}

		if (vexRT(Ch1) == 0)
		{
			stopMotor(clawJoint);
		}
	}
}

/*
	Functions:
	-Open/close claw
	-Move conveyor belt forwards/backwards
*/
task Buttons()
{
	int claw_isOpen = false;

	while (true)
	{
		/*
		  Open/close claw
		  NOTE: Claw must be CLOSED on run (don't want to break anything)
		*/
		if (vexRT(Btn8D) == 1)
		{
			if (claw_isOpen == false)
			{
				startMotor(clawMotor, 63);
				wait(1);
				stopMotor(clawMotor);
				claw_isOpen = true;
			}

			else if (claw_isOpen == true)
			{
				startMotor(clawMotor, -63);
				wait(1);
				stopMotor(clawMotor);
				claw_isOpen = false;
			}
		}

		// Move conveyor belt forward
		if (vexRT(Btn6D) == 1)
		{
			startMotor(rightBelt, 127);
			startMotor(leftBelt, 127);
		}

		if (vexRT(Btn6D) == 0)
		{
			stopMotor(rightBelt);
			stopMotor(leftBelt);
		}

		// Move conveyor belt backwards
		if (vexRT(Btn5D) == 1)
		{
			startMotor(rightBelt, -127);
			startMotor(leftBelt, -127);
		}

		if (vexRT(Btn5D) == 0)
		{
			stopMotor(rightBelt);
			stopMotor(leftBelt);
		}
	}
}

// Entrypoint
task main()
{
	startTask(LeftJoystick);
	startTask(RightJoystick);
	startTask(Buttons);
}
