#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: VEX Clawbot
  Team Members: Matthew Finerty
  Date: April 24th, 2017
  Section: Robotics


  Task Description: Create a robot that is able to to pick up and place cones


  Pseudocode:
  While true
  	a bunch of if statements and stuff here
  end

*/

task main()
{                                     //Program begins, insert code within curly braces
	bool claw_isOpen = true;

	while (true)
	{

		// Move forward/backwards
		if (vexRT(Ch3)> 0 || vexRT(Ch3) < 0)
		{
			startMotor(leftMotor, vexRT(Ch3));
			startMotor(rightMotor, vexRT(Ch3));
		}

		// Stop when joystick is not active
		if (vexRT(Ch3) == 0)
		{
			stopMotor(leftMotor);
			stopMotor(rightMotor);
		}

		// Turn right
		if (vexRT(Ch4) > 0)
		{
			startMotor(leftMotor, vexRT(Ch4));
			startMotor(rightMotor, vexRT(Ch4)*-1);
		}

		// Turn left
		if (vexRT(Ch4) < 0)
		{
			startMotor(leftMotor, vexRT(Ch4));
			startMotor(rightMotor, vexRT(Ch4)*-1);
		}

		// Stop when joystick is not active
		if (vexRT(Ch4) == 0)
		{
			stopMotor(leftMotor);
			stopMotor(rightMotor);
		}

		/*
			Open/close claw
			NOTE: Claw must be CLOSED on run (don't want to break anything)
		*/
		if (vexRT(Btn8D) == 1)
		{
			if (claw_isOpen == false)
			{
				startMotor(clawMotor, 63);
				wait(1);
				stopMotor(clawMotor);
				claw_isOpen = true;
			}
			if (claw_isOpen == true)
			{
				startMotor(clawMotor, -63);
				wait(1);
				stopMotor(clawMotor);
				claw_isOpen = false;
			}
		}

	}



}
